### ISSUE TITLE
Gatsby plugin/example ?

### ISSUE THREAD

**Issue by revskill10** [jaydenseric/graphql-react#19]
Firstly, thanks you for great work here ! It's such a breath air for a simple design for Graphql !

Secondly, do you have any example/guide on how to use this with Gatsby ?

**Comment by jaydenseric** [comment]
I don't know the best practices for integrating it with Gatsby, but once I release the epic React hooks `graphql-react` rewrite (***very*** soon) we can look into it :)

Keep in mind I don't recommend anyone use Gatsby; [Next.js](https://nextjs.org) is far superior. Gatsby can't SSR dynamic pages.

**Comment by revskill10** [comment]
@jaydenseric I also think about the `hook` part, too, but don't know if it could solve the `async` part.
My main use of Gatsby for me is to serve static data from legacy database system with `knex.js` . My use of graphql is for dynamic part with both nextjs and gatsby. I used both in one project currently.

**Comment by jaydenseric** [comment]
The React hooks rewrite is out in [v8.0.0](https://github.com/jaydenseric/graphql-react/releases/tag/v8.0.0). I'm spending the rest of this week refactoring my current project to use hooks, and once I have something realistic to test against I'll be optimizing the `useGraphQL` hook (avoiding API changes).

Closing because I don't intend to directly support Gatsby like we do Next.js, although feel free to report back here if you discover anything that may help others :)
