### ISSUE TITLE
Wrong type calculation on useGraphQL

### ISSUE THREAD

**Issue by etc-tiago** [jaydenseric/graphql-react#49]
The date object cannot be subtracted

this
https://github.com/jaydenseric/graphql-react/blob/84509154cb6ed72ea1d571f0355bedc2626281cc/src/universal/useGraphQL.js#L205

should be
```js
new Date().getTime() - firstRenderDate < 1000
```

**Comment by jaydenseric** [comment]
While it might be good to use something less confusing than `new Date()` (i.e. `Date.now()`), it is perfectly valid to do subtraction math on `Date` instances because they implement [`@@toPrimitive`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/@@toPrimitive). See [“Why can I do math with Date objects?”](https://stackoverflow.com/a/50793100/1596978) on Stack Overflow.

Thanks for the concern though, and looking over the details! Maybe we can tweak it to be less confusing :)
