### ISSUE TITLE
graphql-react example script not working.

### ISSUE THREAD

**Issue by pur3miish** [jaydenseric/graphql-react#5]
The example script fails.

`git clone https://github.com/jaydenseric/graphql-react.git && cd graphql-react/example && npm install && npm run dev
`

Returns: 
> TypeError: Object(...) is not a function

**Comment by jaydenseric** [comment]
That’s because master branch has unpublished changes. To try out the latest unpublished API, run ‘npm install’ in the cloned directory, then in ‘example/package.json’ change the ‘graphql-react’ dependency to ‘file:..’.

I want to make this easier soon, and deploy a live example with Zeit Now.

I have a newer API I hope to push in the next few hours, so keep that in mind 🙂
