### ISSUE TITLE
Allow React component displayName and propTypes to be removed in production builds

### ISSUE THREAD

**Issue by hc-codersatlas** [jaydenseric/graphql-react#51]
Hi, can proptypes be removed from the production builds? Saves ~3kb. It's good for development but would be better if it's not exported out. Thanks.

Can be done via a [babel plugin](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types).

**Comment by jaydenseric** [comment]
Yes, it is a good idea to avoid [`prop-types`](https://npm.im/prop-types) in production bundles, but the actually elimination of it should happen when a user builds their project; we don't publish separate development and production versions of `graphql-react`. We should however make sure what we publish works well with tooling such as Webpack via Next.js.

I had just assumed that Next.js eliminates `prop-types` in production builds for both project code _and_ dependencies, but I do wonder if maybe that's not true - it would be good to test it out.

To be sure, we should conditionally define `propTypes` on components via a `process.env.NODE_ENV !== 'production'` condition, like how other packages such as `react-redux` does it:

https://github.com/reduxjs/react-redux/blob/f0124d71f959224fd1aebc02d50ce0069e58c5e5/src/components/Provider.js#L36-L37

I'm not a fan of using `process.env.NODE_ENV` because that won't work without a bundler; `process` is undefined in a browser. Maybe there should be a more complicated `typeof process !== 'undefined' && process.env.NODE_ENV` check.

**Comment by jaydenseric** [comment]
So, this would be a breaking change for anyone that doesn't have a bunder that deals with `process` being undefined in browsers (or any non-Node.js environment really):

<img width="1147" alt="Screen Shot 2020-09-17 at 1 24 09 pm" src="https://user-images.githubusercontent.com/1754873/93416504-495b2580-f8e9-11ea-823b-a0df641c9a2e.png">

Although it's a little more verbose, this is not a breaking change:

<img width="1157" alt="Screen Shot 2020-09-17 at 1 23 13 pm" src="https://user-images.githubusercontent.com/1754873/93416602-65f75d80-f8e9-11ea-803a-d10d1c8b5444.png">

Here they are compared in a Next.js production build:

<img width="960" alt="Screen Shot 2020-09-17 at 1 28 37 pm" src="https://user-images.githubusercontent.com/1754873/93416770-c71f3100-f8e9-11ea-925c-3cbd33580b87.png">

The `propTypes` are successfully eliminated for both, although the second option causes _slightly_ more complicated code for some reason beyond my understanding.

**Comment by jaydenseric** [comment]
This improvement has been published in [v11.1.0](https://github.com/jaydenseric/graphql-react/releases/tag/v11.1.0) 🚀
